services:
  - type: web
    name: gpt-docs-proxy
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app_flask.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
    healthCheckPath: /health
    autoDeploy: true
