services:
  - type: web
    name: gpt-docs-proxy
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port app_flask:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
    healthCheckPath: /health
    autoDeploy: true
